### PR TITLE
Add exceptions for command-line apps shipped as part of freedesktop-sdk

### PR DESCRIPTION
**Pull request by nanonyme**

### CODE REVIEW

**Comment by nanonyme** [comment]
@barthalion looks like it requires another pipeline approval after force push.

**Comment by bbhtt** [comment]
The CI will be fixed if you rebase, there's also conflicts.

**Comment by nanonyme** [comment]
@bbhtt it's a bit tiresome this needs a separate approval on every rebase.

**Comment by bbhtt** [comment]
> @bbhtt it's a bit tiresome CI needs a separate approval on every rebase.

Yea, I approved it.

**Comment by nanonyme** [comment]
I guess this has to be approved for CI again

**Pull request closed without merging**
