### PR TITLE
Add flatpak-spawn exception for Bavarder

### PR DESCRIPTION
**Pull request by 0xMRTT**
Bavarder needs this for running commands in the shell

Screenshot from 2023-08-20 14-20-29

### CODE REVIEW

**Comment by 0xMRTT** [comment]
Hey, can someone merge this ? Thanks !!

**Comment by hfiguiere** [comment]
Can you rebase (instead of merge) so that there is only one commit?

**Comment by 0xMRTT** [comment]
@hfiguiere  https://github.com/flathub/flatpak-builder-lint/pull/171 replace it!

**Comment by hfiguiere** [comment]
you didn't need to replace

**Pull request closed without merging**
