### PR TITLE
Add exemption for io.github.betaflight.BetaflightConfigurator

### PR DESCRIPTION
**Pull request by razzeee**

### CODE REVIEW

**Comment by razzeee** [comment]
https://buildbot.flathub.org/#/builders/26/builds/2451

**Comment by barthalion** [comment]
It shouldn't need access to the entire system bus. Did you try to nail down specific names with `--log-system-bus`?

**Comment by hfiguiere** [comment]
`    "--system-talk-name=org.freedesktop.UPower"` doesn't work?

**Comment by razzeee** [comment]
> ` "--system-talk-name=org.freedesktop.UPower"` doesn't work?

It didn't, when I used flatseal, but let me do it again, as a sanity check.

**Comment by razzeee** [comment]
Nevermind, seems like I confused `talk` with `system-talk`...

**Pull request closed without merging**
